name: Deploy to Hugging Face Spaces

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_USERNAME: JayAtriahf-7
          SPACE_NAME: SkySense-Flight-Price-Predictor
        run: |
          if [ -z "$HF_TOKEN" ]; then echo "HF_TOKEN secret missing (add in GitHub repo settings)"; exit 1; fi
          git remote add hf https://$HF_USERNAME:$HF_TOKEN@huggingface.co/spaces/$HF_USERNAME/$SPACE_NAME || true
          # Push current branch HEAD to Space main; --force ensures mirror (Space is the deploy target)
          git push hf HEAD:main --force
