name: Deploy to Hugging Face Spaces

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"

      - name: Prepare Space bundle (exclude large datasets)
        run: |
          set -e
          mkdir -p space_dist
          # Copy only what the Space needs
          cp -R backend space_dist/
          cp -R web space_dist/
          cp requirements.txt space_dist/
          cp Dockerfile space_dist/
          # Optional: minimal README for the Space
          if [ -f README.md ]; then cp README.md space_dist/; fi
          # Clean up caches/artifacts
          rm -rf space_dist/backend/__pycache__ || true
          rm -rf space_dist/backend/*.joblib || true
          rm -rf space_dist/logs || true
          # Ensure datasets are NOT included
          rm -f space_dist/*.csv || true

      - name: Push to Hugging Face Space
        env:
          # Prefer repository/organization secret; fallback to repository variable if secret is missing
          HF_TOKEN: ${{ secrets.HF_TOKEN || vars.HF_TOKEN }}
          HF_USERNAME: JayAtriahf-7
          SPACE_NAME: SkySense-Flight-Price-Predictor
        run: |
          if [ -z "$HF_TOKEN" ]; then echo "HF_TOKEN secret missing (add in GitHub repo settings)"; exit 1; fi
          echo "Preparing temporary git repo for Space deployment"
          cd space_dist
          git init
          git checkout -b main
          # Configure author identity for this temporary repo
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git add .
          git commit -m "Deploy $GITHUB_SHA to HF Space"
          git remote add hf https://$HF_USERNAME:$HF_TOKEN@huggingface.co/spaces/$HF_USERNAME/$SPACE_NAME
          git push hf main --force
